// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD_QGgDw6ykC5DTXqq3eJpUvzIKaNDZzw',
    appId: '1:143015024721:web:2cb7f3912577303652c070',
    messagingSenderId: '143015024721',
    projectId: 'ninja-brew-crew-faa27',
    authDomain: 'ninja-brew-crew-faa27.firebaseapp.com',
    databaseURL: 'https://ninja-brew-crew-faa27-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ninja-brew-crew-faa27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiXmt5HtOdF9C5-h3C5wD7YJu-HX9Z1Tw',
    appId: '1:143015024721:android:edbfdfad615d24d752c070',
    messagingSenderId: '143015024721',
    projectId: 'ninja-brew-crew-faa27',
    databaseURL: 'https://ninja-brew-crew-faa27-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ninja-brew-crew-faa27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Ihc4JOAsfuActRfpy5Tan8KDPczmbYo',
    appId: '1:143015024721:ios:6016f2e059aaba7552c070',
    messagingSenderId: '143015024721',
    projectId: 'ninja-brew-crew-faa27',
    databaseURL: 'https://ninja-brew-crew-faa27-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ninja-brew-crew-faa27.appspot.com',
    iosBundleId: 'com.example.basicsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Ihc4JOAsfuActRfpy5Tan8KDPczmbYo',
    appId: '1:143015024721:ios:6eec2f0dca7954e452c070',
    messagingSenderId: '143015024721',
    projectId: 'ninja-brew-crew-faa27',
    databaseURL: 'https://ninja-brew-crew-faa27-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ninja-brew-crew-faa27.appspot.com',
    iosBundleId: 'com.example.basicsFirebase.RunnerTests',
  );
}
